### PR TITLE
Fix NullPointerException while using with Clover

### PR DESCRIPTION
**Pull request by poikilotherm**
Hi @f-lopes,

I really appreciate your little helper utility, but stumbled over NullPointerException while using your helper in my MVC unit tests in combination with [Clover coverage reporting](http://openclover.org/).

In [Line 185](https://github.com/poikilotherm/spring-mvc-test-utils/blob/4913a6904cc64611ff9e729d5da44a93f78db5f1/src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java#L185) your are testing with `getSuperClass()`, which may return `null`. Without using Clover, everything works just fine, but using Clover the code instrumentation seems to alter the result and we hit a `NullPointerException`.

I added some simple `null` handling code and it runs smoothly again. :smile: 

I would really appreciate if you could merge this and release a new version to Maven Central. Thanks!

Cheers
Oliver

P.S.: Sorry for not sharing a code example for demonstration purposes, this is a project not yet released to the public (but will be as open source...).

### CODE REVIEW

**Comment by poikilotherm** [comment]
Done. Removed my addition to pom.xml, so you can set the release version yourself... :smile:

**Comment by f-lopes** [comment]
The version 1.0.2 containing your pull request has been released, it should be available soon. Thanks

**Comment by poikilotherm** [comment]
Thank you very much - already using it in my jobs, working like a charm. :+1:

**Comment by f-lopes** [comment]
Thanks for your feedback. 😄

**Pull request merged**
