### PR TITLE
Add configuration class to exclude specific fields

### LINKED ISSUE #175: Exclude static and transient fields from form fields by default
Hello,

after introducing a Comparator constant to a model class, we're running into issues with certain fields in that comparator not being accessible to reflection. After some digging I found out that this library includes both static and transient fields in the generated form data.

Since most libraries with similar functionality (e.g. JSON Libraries) don't include such fields, I would like to suggest to exclude static and transient fields either alltogether or as a default, but configurable behaviour.

The code change would probably fit into getAllNonSyntheticFields to also exclude aforementioned fields. I would be happy to provide a pull request if there's any interest. 

Greetings,
schosins

### PR DESCRIPTION
**Pull request by schosin**
This PR adds a configuration class to exclude fields based on a predicate. In addition static and final fields will always be excluded and transient fields will be excluded by default.

See initial discussion in #175. 

Resolves #175

- - -
This change is [Reviewable](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177)

### CODE REVIEW

**Review by f-lopes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @f-lopes and @schosin)

___
*[`src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java` line 175 at r1](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-N8mQAYe5ke9jlM8kV9E:-N8mQAYe5ke9jlM8kV9F:blkmivm) ([raw file](https://github.com/f-lopes/spring-mvc-test-utils/blob/d7b16b608e646ce024621667788e77aa4b0a5c9e/src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java#L175)):*
> ```Java
>         return FieldUtils.getAllFieldsList(form.getClass())
>                 .stream()
>                 .filter(config.fieldPredicate::test)
> ```

May this be simplified? `.filter(config.fieldPredicate)`
___
*[`src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java` line 313 at r1](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-N8mRW352aK6fLJJ4PZv:-N8mRW352aK6fLJJ4PZw:b-rj4d0g) ([raw file](https://github.com/f-lopes/spring-mvc-test-utils/blob/d7b16b608e646ce024621667788e77aa4b0a5c9e/src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java#L313)):*
> ```Java
>         public static class Builder {
> 
>             private static final Predicate<Field> BASE_PREDICATE = Builder::isNotSyntheticStaticFinal;
> ```

Wouldn't it be better to add this predicate explicitly to the default config (https://github.com/f-lopes/spring-mvc-test-utils/pull/177/files#diff-76590759ae638aa1c6a929438bd9b76ea78257df054f65c8b20f1890f11003a4R313) rather than hiding it (from the client) in this Builder class?

```
private static final Configuration DEFAULT_CONFIG = Configuration.builder()
.includeSynthetic(false)
.includeStatic(false)
.includeFinal(false)
.build();
```
This way, we would instantly see the default config without having to search in the `Builder` class.
___
*[`src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java` line 329 at r1](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-N8mQw_4CDHPlvRrupDc:-N8mQw_4CDHPlvRrupDd:brj2sn6) ([raw file](https://github.com/f-lopes/spring-mvc-test-utils/blob/d7b16b608e646ce024621667788e77aa4b0a5c9e/src/main/java/io/florianlopes/spring/test/web/servlet/request/MockMvcRequestBuilderUtils.java#L329)):*
> ```Java
> 
>             public Configuration build() {
>                 var fieldPredicate = BASE_PREDICATE;
> ```

In order to match the rest of the codebase, could this line include the type instead of var (`Predicate<Field>`)?

**Review by f-lopes — COMMENTED** [review]
Thanks again for your contribution. 👍 

Perfect P-R:
* matching code style
* improved coverage

After more consideration, I think excluding `final` fields may be too restrictive/opinionated if you want to make your form immutable (which is generally a good practice).
Doing some smoke tests without excluding `final` fields by default, I found that Spring does include them. So how did you conclude that Spring doesn't populate them (https://github.com/f-lopes/spring-mvc-test-utils/issues/175#issuecomment-1204915302)?

I have also added some minor suggestions for reflection.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-:-N8mTLxPCRgLTBpoOwv1:b-lq4vku)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @f-lopes and @schosin)

**Comment by schosin** [comment]
I agree regarding final. I'm using `private final List<Whatever>` myself all the time. I will also change the other two suggestions.

Would including `.includeSynthetic(false)` and `.includeStatic(false)` really help? That would indicate you can include those and those don't make sense to include in a form post, do they?

I will get to it on monday when I'm back at work. Cheers.

**Comment by f-lopes** [comment]
> I agree regarding final. I'm using private final List<Whatever> myself all the time. I will also change the other two suggestions.

Thanks! I also use it all the time!

> Would including .includeSynthetic(false) and .includeStatic(false) really help? That would indicate you can include those and those don't make sense to include in a form post, do they?

Not that it would make a lot of sense, but the default behavior would be indicated through this field, in my opinion. "The authors have made an opinionated choice regarding those fields, and it's clearly visible, not somewhat hidden." It would also let the user select those fields if needed.

Of course, enjoy your weekend!

**Comment by schosin** [comment]
Made the requested changes. I haven't included a `includeSynthetic` as those cause a StackOverflowError when combined with inner classes. Including non-user code would be strange anyway, wouldn't it?

**Review by f-lopes — COMMENTED** [review]
Thanks for the changes.

I have also brought some minor changes. Let me know if you don't agree:

- explicitly added the default config at the top of the class showing straight what the default config is about.

- removed the null-checks at lines 351, 355 and 359. `BASE_PREDICATE` seems always initialized.

Thanks!

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-:-N8yqAg2CpDFXtvvmqyN:bfk1l)* status: all files reviewed, 3 unresolved discussions (waiting on @schosin)

**Review by f-lopes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/f-lopes/spring-mvc-test-utils/177#-:-N8ysMbP3GNtui1xKPOZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @schosin)

**Comment by schosin** [comment]
Looks good to me 👍

**Comment by f-lopes** [comment]
I will release it as soon as I can.

I have to rework the release job as TravisCI.org has been discontinued. Also, my deploy key expired 1month ago.

**Comment by f-lopes** [comment]
Released, should be available shortly: 
https://mvnrepository.com/artifact/io.florianlopes/spring-mvc-test-utils 
https://search.maven.org/artifact/io.florianlopes/spring-mvc-test-utils/3.2.0/jar

**Comment by f-lopes** [comment]
Here is the 3.2.0 release:
https://github.com/f-lopes/spring-mvc-test-utils/releases/tag/v3.2.0

```xml
<dependency>
  <groupId>io.florianlopes</groupId>
  <artifactId>spring-mvc-test-utils</artifactId>
  <version>3.2.0</version>
</dependency>
```

Thanks for your contribution!

**Pull request merged**
